<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CartesTrucadesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cartes_trucades')->delete();
        
        \DB::table('cartes_trucades')->insert(array (
            0 => 
            array (
                'id' => 1,
                'codi_trucada' => '1',
                'data_hora' => '2022-03-30 11:27:12',
                'temps_trucada' => 9000,
                'dades_personals_id' => 1,
                'telefon' => '123456789',
                'procedencia_trucada' => 'Francès',
                'origen_trucada' => 'Pl Catalunya',
                'nom_trucada' => 'Pepe González',
                'municipis_id_trucada' => 91,
                'adreca_trucada' => 'Pl Catalunya 5, pis 4',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 1,
                'descripcio_localitzacio' => 'Plaça Catalunya, cantonada tocant amb les rambles',
                'detall_localitzacio' => 'A l\'entrada del fnac.',
                'altres_ref_localitzacio' => NULL,
                'incidents_id' => 1,
                'nota_comuna_descripcio' => 'Nota comuna describint l\'incidenttttttttttttttttttttttttttttttttttttttttttttttttt',
                'expedients_id' => 1,
                'usuaris_id' => 2,
            ),
            1 => 
            array (
                'id' => 2,
                'codi_trucada' => '2',
                'data_hora' => '2022-03-30 11:27:12',
                'temps_trucada' => 90,
                'dades_personals_id' => 1,
                'telefon' => '123456789',
                'procedencia_trucada' => 'Francès',
                'origen_trucada' => 'Pl Catalunya',
                'nom_trucada' => 'Pepe González',
                'municipis_id_trucada' => 91,
                'adreca_trucada' => 'Pl Catalunya 5, pis 4',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 1,
                'descripcio_localitzacio' => 'Plaça Catalunya, cantonada tocant amb les rambles',
                'detall_localitzacio' => 'A l\'entrada del fnac.',
                'altres_ref_localitzacio' => NULL,
                'incidents_id' => 1,
                'nota_comuna_descripcio' => 'Nota comuna describint l\'incident',
                'expedients_id' => 1,
                'usuaris_id' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'codi_trucada' => '3',
                'data_hora' => '2022-03-30 11:27:12',
                'temps_trucada' => 90,
                'dades_personals_id' => 1,
                'telefon' => '123456789',
                'procedencia_trucada' => 'Francès',
                'origen_trucada' => 'Pl Catalunya',
                'nom_trucada' => 'Pepe González',
                'municipis_id_trucada' => 91,
                'adreca_trucada' => 'Pl Catalunya 5, pis 4',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 1,
                'descripcio_localitzacio' => 'Plaça Catalunya, cantonada tocant amb les rambles',
                'detall_localitzacio' => 'A l\'entrada del fnac.',
                'altres_ref_localitzacio' => NULL,
                'incidents_id' => 1,
                'nota_comuna_descripcio' => 'Nota comuna describint l\'incident',
                'expedients_id' => 2,
                'usuaris_id' => 2,
            ),
            3 => 
            array (
                'id' => 4,
                'codi_trucada' => '4',
                'data_hora' => '2022-04-04 11:27:12',
                'temps_trucada' => 30,
                'dades_personals_id' => 1,
                'telefon' => '645245851',
                'procedencia_trucada' => 'Català',
                'origen_trucada' => 'Sagrada familia',
                'nom_trucada' => 'Jose Mandunguilla',
                'municipis_id_trucada' => 91,
                'adreca_trucada' => 'Pl Catalunya 5, pis 4',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 1,
                'descripcio_localitzacio' => 'Sagrada famila al costat de la benzinera',
                'detall_localitzacio' => 'benzinera',
                'altres_ref_localitzacio' => NULL,
                'incidents_id' => 211,
                'nota_comuna_descripcio' => 'Incident perill persona al costat de la benzinera',
                'expedients_id' => 4,
                'usuaris_id' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'codi_trucada' => '5',
                'data_hora' => '2022-04-03 11:27:12',
                'temps_trucada' => 24,
                'dades_personals_id' => 1,
                'telefon' => '645245851',
                'procedencia_trucada' => 'Català',
                'origen_trucada' => 'Sagrada familia',
                'nom_trucada' => 'Antonia croqueta',
                'municipis_id_trucada' => 91,
                'adreca_trucada' => 'Pl Catalunya 5, pis 4',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 1,
                'descripcio_localitzacio' => 'Sagrada famila al costat de la benzinera',
                'detall_localitzacio' => 'benzinera',
                'altres_ref_localitzacio' => NULL,
                'incidents_id' => 128,
                'nota_comuna_descripcio' => 'Incident perill persona al costat de la benzinera',
                'expedients_id' => 2,
                'usuaris_id' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'codi_trucada' => '6',
                'data_hora' => '2022-04-03 11:27:12',
                'temps_trucada' => 24,
                'dades_personals_id' => 1,
                'telefon' => '645245851',
                'procedencia_trucada' => 'Català',
                'origen_trucada' => 'Sagrada familia',
                'nom_trucada' => 'Antonia croqueta',
                'municipis_id_trucada' => 91,
                'adreca_trucada' => 'Pl Catalunya 5, pis 4',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 1,
                'descripcio_localitzacio' => 'Sagrada famila al costat de la benzinera',
                'detall_localitzacio' => 'benzinera',
                'altres_ref_localitzacio' => NULL,
                'incidents_id' => 128,
                'nota_comuna_descripcio' => 'Incident perill persona al costat de la benzinera',
                'expedients_id' => 6,
                'usuaris_id' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'codi_trucada' => '7',
                'data_hora' => '2022-04-03 11:27:12',
                'temps_trucada' => 12,
                'dades_personals_id' => 1,
                'telefon' => '645245851',
                'procedencia_trucada' => 'Castellano',
                'origen_trucada' => 'Sagrada familia',
                'nom_trucada' => 'Juan Chedar',
                'municipis_id_trucada' => 91,
                'adreca_trucada' => 'Pl Catalunya 5, pis 4',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 1,
                'descripcio_localitzacio' => 'Sagrada famila al costat de la benzinera',
                'detall_localitzacio' => 'benzinera',
                'altres_ref_localitzacio' => NULL,
                'incidents_id' => 115,
                'nota_comuna_descripcio' => 'Incident perill persona al costat de la benzinera',
                'expedients_id' => 5,
                'usuaris_id' => 1,
            ),
            7 => 
            array (
                'id' => 9,
                'codi_trucada' => 'CA-010520222013252',
                'data_hora' => '2022-05-01 20:13:25',
                'temps_trucada' => 201,
                'dades_personals_id' => 3,
                'telefon' => '666148666',
                'procedencia_trucada' => 'Mongolia',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 91,
                'adreca_trucada' => 'Calle de Santiago',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Barcelona Barcelonès Barcelona',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'Barcelona centro, barrio gay que es donde Santi siempre va.',
                'incidents_id' => 12,
                'nota_comuna_descripcio' => 'Santiago Maresca Thome, víctima del incidente, 666148852, Estaba paseando por la calle y se le cayó un pene de metal en la cabeza.',
                'expedients_id' => 35,
                'usuaris_id' => 1,
            ),
            8 => 
            array (
                'id' => 10,
                'codi_trucada' => 'CA-010520222022174',
                'data_hora' => '2022-05-01 20:22:17',
                'temps_trucada' => 350,
                'dades_personals_id' => NULL,
                'telefon' => '666555333',
                'procedencia_trucada' => 'Catalunya',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 91,
                'adreca_trucada' => 'Plaça Urquinaona 10',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 2,
                'descripcio_localitzacio' => 'Plaça urquinaona, Barcelona',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'Edifici del Centre d\'Estudis Politècnics',
                'incidents_id' => 25,
                'nota_comuna_descripcio' => 'Centre d\'Estudis Politècnics
Informant de l\'incident
987654321
Un alumne ha caigut per les escales',
                'expedients_id' => 35,
                'usuaris_id' => 1,
            ),
            9 => 
            array (
                'id' => 12,
                'codi_trucada' => 'CA-010520222030564',
                'data_hora' => '2022-05-01 20:30:56',
                'temps_trucada' => 19,
                'dades_personals_id' => NULL,
                'telefon' => '123456678',
                'procedencia_trucada' => 'asd',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 6,
                'adreca_trucada' => 'asd',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Barcelona Barcelonès Barcelona',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'asd',
                'incidents_id' => 5,
                'nota_comuna_descripcio' => 'asd',
                'expedients_id' => 36,
                'usuaris_id' => 1,
            ),
            10 => 
            array (
                'id' => 13,
                'codi_trucada' => 'CA-010520222031419',
                'data_hora' => '2022-05-01 20:31:41',
                'temps_trucada' => 16,
                'dades_personals_id' => NULL,
                'telefon' => '111111111',
                'procedencia_trucada' => 'asd',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 4,
                'adreca_trucada' => 'asd',
                'fora_catalunya' => 0,
                'provincies_id' => 2,
                'municipis_id' => 9,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Girona Gironès Aiguaviva',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'asd',
                'incidents_id' => 6,
                'nota_comuna_descripcio' => 'asd',
                'expedients_id' => 37,
                'usuaris_id' => 1,
            ),
            11 => 
            array (
                'id' => 15,
                'codi_trucada' => 'CA-010520222033478',
                'data_hora' => '2022-05-01 20:33:47',
                'temps_trucada' => 16,
                'dades_personals_id' => NULL,
                'telefon' => '123456789',
                'procedencia_trucada' => 'aa',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 6,
                'adreca_trucada' => 'aa',
                'fora_catalunya' => 0,
                'provincies_id' => 3,
                'municipis_id' => 13,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Lleida Garrigues L\'Albagés',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'aa',
                'incidents_id' => 8,
                'nota_comuna_descripcio' => 'aa',
                'expedients_id' => 39,
                'usuaris_id' => 1,
            ),
            12 => 
            array (
                'id' => 17,
                'codi_trucada' => 'CA-010520222055047',
                'data_hora' => '2022-05-01 20:55:04',
                'temps_trucada' => 14,
                'dades_personals_id' => NULL,
                'telefon' => '987654321',
                'procedencia_trucada' => 'asd',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 9,
                'adreca_trucada' => 'asd',
                'fora_catalunya' => 0,
                'provincies_id' => 3,
                'municipis_id' => 10,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Lleida Segrià Aitona',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'asd',
                'incidents_id' => 6,
                'nota_comuna_descripcio' => 'asd',
                'expedients_id' => 41,
                'usuaris_id' => 1,
            ),
            13 => 
            array (
                'id' => 18,
                'codi_trucada' => 'CA-010520222057070',
                'data_hora' => '2022-05-01 20:57:07',
                'temps_trucada' => 23,
                'dades_personals_id' => NULL,
                'telefon' => '123456789',
                'procedencia_trucada' => 'asd',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 2,
                'adreca_trucada' => 'asd',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Barcelona Barcelonès Barcelona',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'asd',
                'incidents_id' => 5,
                'nota_comuna_descripcio' => 'asd',
                'expedients_id' => 42,
                'usuaris_id' => 1,
            ),
            14 => 
            array (
                'id' => 19,
                'codi_trucada' => 'CA-010520222157345',
                'data_hora' => '2022-05-01 21:57:34',
                'temps_trucada' => 37,
                'dades_personals_id' => NULL,
                'telefon' => '777777777',
                'procedencia_trucada' => 'procedencia',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 4,
                'adreca_trucada' => 'adreça',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Barcelona Barcelonès Barcelona',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'informació rellevant',
                'incidents_id' => 6,
                'nota_comuna_descripcio' => 'nota comuna',
                'expedients_id' => 42,
                'usuaris_id' => 1,
            ),
            15 => 
            array (
                'id' => 20,
                'codi_trucada' => 'CA-010520222201110',
                'data_hora' => '2022-05-01 22:01:11',
                'temps_trucada' => 103,
                'dades_personals_id' => NULL,
                'telefon' => '222222222',
                'procedencia_trucada' => 'asd',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 1,
                'adreca_trucada' => 'adreççççççççççça',
                'fora_catalunya' => 0,
                'provincies_id' => 3,
                'municipis_id' => 3,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Lleida Noguera Àger',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'asd',
                'incidents_id' => 5,
                'nota_comuna_descripcio' => 'asd',
                'expedients_id' => 43,
                'usuaris_id' => 1,
            ),
            16 => 
            array (
                'id' => 21,
                'codi_trucada' => 'CA-010520222203524',
                'data_hora' => '2022-05-01 22:03:52',
                'temps_trucada' => 29,
                'dades_personals_id' => NULL,
                'telefon' => '99999999',
                'procedencia_trucada' => 'asd',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 2,
                'adreca_trucada' => NULL,
                'fora_catalunya' => 0,
                'provincies_id' => 3,
                'municipis_id' => 4,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Lleida Urgell Agramunt',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'asd',
                'incidents_id' => 4,
                'nota_comuna_descripcio' => 'asd',
                'expedients_id' => 44,
                'usuaris_id' => 1,
            ),
            17 => 
            array (
                'id' => 22,
                'codi_trucada' => 'CA-010520222228392',
                'data_hora' => '2022-05-01 22:28:39',
                'temps_trucada' => 36,
                'dades_personals_id' => NULL,
                'telefon' => '111222333',
                'procedencia_trucada' => 'poiuytrewq',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 1,
                'adreca_trucada' => 'adreca',
                'fora_catalunya' => 0,
                'provincies_id' => 1,
                'municipis_id' => 91,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Barcelona Barcelonès Barcelona',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'asdasdasdasdasd',
                'incidents_id' => 1,
                'nota_comuna_descripcio' => 'asd',
                'expedients_id' => 42,
                'usuaris_id' => 1,
            ),
            18 => 
            array (
                'id' => 23,
                'codi_trucada' => 'CA-010520222242135',
                'data_hora' => '2022-05-01 22:42:13',
                'temps_trucada' => 25,
                'dades_personals_id' => NULL,
                'telefon' => '112233445',
                'procedencia_trucada' => 'asd',
                'origen_trucada' => NULL,
                'nom_trucada' => NULL,
                'municipis_id_trucada' => 12,
                'adreca_trucada' => 'asd',
                'fora_catalunya' => 0,
                'provincies_id' => 3,
                'municipis_id' => 4,
                'tipus_localitzacions_id' => 3,
                'descripcio_localitzacio' => 'Lleida Urgell Agramunt',
                'detall_localitzacio' => NULL,
                'altres_ref_localitzacio' => 'asd',
                'incidents_id' => 7,
                'nota_comuna_descripcio' => 'asd',
                'expedients_id' => 45,
                'usuaris_id' => 1,
            ),
        ));
        
        
    }
}